apiVersion: v1
kind: Service
metadata:
  name: webook-live-1
spec:
  type: LoadBalancer
  selector:
    app: webook-live-1
  ports:
# Cluster IP
    - protocol: TCP
      name: http
      port: 81
      targetPort: 8080

  